In [ ]:
#EXPERIMENT-2: Perform Different Array Slicing Methods

import numpy as np
my_array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("\n slicing the first two rows & columns:")
print(my_array[:2,:2])
print("\n slicing the last row:")
print(my_array[2:])
print("\n slicing the second column:")
print(my_array[:,1])
print("\n slicing with a step:")
print(my_array[::2,::2])


 slicing the first two rows & columns:
[[1 2]
 [4 5]]

 slicing the last row:
[[7 8 9]]

 slicing the second column:
[2 5 8]

 slicing with a step:
[[1 3]
 [7 9]]
